

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Header from '../../../components/header';
import Footer from '../../../components/footer';
import Sidebar from '../../../components/sidebar';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className='w-screen h-screen flex flex-col'>
        <Header />
        <div className='w-screen flex'>
            <Sidebar />
            {children}
        </div>
        <Footer />
        </div></body>
        
    </html>
  )
}
